apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-config
  namespace: demo-app
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS demo_db;
    USE demo_db;

    CREATE TABLE IF NOT EXISTS messages (
        id INT AUTO_INCREMENT PRIMARY KEY,
        message VARCHAR(255) NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    INSERT INTO messages (message) VALUES ('Hello from Kubernetes on EC2!');
    INSERT INTO messages (message) VALUES ('MySQL with persistent storage');
    INSERT INTO messages (message) VALUES ('DNS service discovery working');
    INSERT INTO messages (message) VALUES ('LoadBalancer service exposed');
    INSERT INTO messages (message) VALUES ('ConfigMaps and Secrets configured');
